# Generated by Django 4.1.7 on 2023-03-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postvotes',
            unique_together=set(),
        ),
    ]
