# Generated by Django 4.1.7 on 2023-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_downvotes_reply_upvotes_replyvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter Post Title', max_length=100),
        ),
    ]
