# Generated by Django 4.1.7 on 2023-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_events_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="thumbnail",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
