# Generated by Django 4.1.7 on 2023-03-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_events_image_alter_events_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="image",
            new_name="image_data",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="thumbnail",
            new_name="thumbnail_data",
        ),
    ]
