# Generated by Django 4.1.7 on 2023-03-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_image_events_image_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="image_data",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="thumbnail_data",
            new_name="thumbnail",
        ),
    ]
