# Generated by Django 4.1.7 on 2023-03-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_rename_image_data_events_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="events",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
