# Generated by Django 4.1.7 on 2023-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_image_alter_events_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
