# Generated by Django 4.1.7 on 2023-03-19 16:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_image_alter_events_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(default=datetime.datetime(2023, 3, 19, 16, 40, 53, 688293, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
