# Generated by Django 4.1.7 on 2023-03-23 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_image_alter_events_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 3, 23, 12, 0, 35, 499192, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(default=datetime.datetime(2023, 3, 23, 12, 7, 41, 548831, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
